CREATE TABLE `sys_task` (
                            `id` int NOT NULL AUTO_INCREMENT COMMENT '任务id',
                            `created_at` datetime(3) DEFAULT NULL,
                            `updated_at` datetime(3) DEFAULT NULL,
                            `deleted_at` datetime(3) DEFAULT NULL,
                            `task_name` varchar(32) NOT NULL COMMENT '任务名称',
                            `task_group` varchar(255) NOT NULL COMMENT '任务分组',
                            `cron_expression` varchar(64) NOT NULL COMMENT 'cron_expression',
                            `invoke_target` varchar(255) NOT NULL,
                            `args` varchar(255) DEFAULT NULL,
                            `http_method` varchar(50) DEFAULT NULL COMMENT 'http_method',
                            `timeout` bigint DEFAULT NULL COMMENT '任务执行超时时间(单位秒),0不限制',
                            `multi` tinyint DEFAULT NULL COMMENT '是否允许多实例运行',
                            `retry_times` tinyint DEFAULT NULL COMMENT '重试次数',
                            `retry_interval` bigint DEFAULT NULL COMMENT '重试间隔时间',
                            `tag` varchar(32) DEFAULT NULL,
                            `remark` varchar(100) DEFAULT NULL,
                            `status` tinyint DEFAULT NULL COMMENT '状态 1:正常 0:停止',
                            PRIMARY KEY (`id`) USING BTREE,
                            KEY `IDX_sys_task_status` (`status`) USING BTREE,
                            KEY `idx_sys_task_deleted_at` (`deleted_at`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sys_task_log` (
                                `id` bigint NOT NULL AUTO_INCREMENT,
                                `task_id` smallint DEFAULT NULL COMMENT '任务id',
                                `task_name` varchar(32) DEFAULT NULL COMMENT '任务名称',
                                `cron_expression` varchar(64) DEFAULT NULL COMMENT 'cron_expression',
                                `invoke_target` varchar(256) DEFAULT NULL COMMENT 'invoke_target',
                                `timeout` bigint DEFAULT NULL,
                                `retry_times` tinyint DEFAULT NULL,
                                `start_time` datetime(3) DEFAULT NULL,
                                `end_time` datetime(3) DEFAULT NULL,
                                `status` tinyint DEFAULT NULL,
                                `result` varchar(191) DEFAULT NULL,
                                `total_time` mediumint DEFAULT NULL,
                                `created_at` datetime(3) DEFAULT NULL,
                                `updated_at` datetime(3) DEFAULT NULL,
                                `deleted_at` datetime(3) DEFAULT NULL,
                                PRIMARY KEY (`id`) USING BTREE,
                                KEY `IDX_sys_log_task_id` (`task_id`),
                                KEY `IDX_sys_log_status` (`status`),
                                KEY `idx_sys_task_log_deleted_at` (`deleted_at`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;